language: node_js
node_js:
  - "10"

script:
  - npm run generate

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: $S3_REGION
  skip_cleanup: true
  local_dir: dist
  acl: public_read
